// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzBYjJCuwhVcgIEg_n8j18K8Dn-Sz0Ib8',
    appId: '1:375984609441:web:e91ab1bf645614a86638e0',
    messagingSenderId: '375984609441',
    projectId: 'firebase-blog-app-oosu',
    authDomain: 'fir-blog-app-oosu.firebaseapp.com',
    storageBucket: 'firebase-blog-app-oosu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgWZn5O7ZVfv4yuxzbVo-rq-n_H3z0N0',
    appId: '1:375984609441:android:c1a0cd2016ecc70d6638e0',
    messagingSenderId: '375984609441',
    projectId: 'firebase-blog-app-oosu',
    storageBucket: 'firebase-blog-app-oosu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA24FDpV83yApk-SyNDAr7vbfLwdqcvO7o',
    appId: '1:375984609441:ios:d4c2d24ce31838ee6638e0',
    messagingSenderId: '375984609441',
    projectId: 'firebase-blog-app-oosu',
    storageBucket: 'firebase-blog-app-oosu.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseBlogApp',
  );
}
